# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24b4f13026b019d53a69cff8c89a986e987da7ad1cdf39bce9f818a61c98ea41ac823e83a862c1cc2ed4f8e9dbed7311d539a13043c9baa956ba9935e09e1868

test:
  secret_key_base: 08219d56926a835d85c17dc82127662b02648b863e8b857f58a9a0c05756c64407de4b1df387428c686e404fd4e19ae7c64c1a611035256d9a3fb874ac00f272

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
